#!/usr/bin/env python3
"""Generate per-workspace pill colors for waybar.

Reads ~/.config/hyprmural/hyprmural.conf, extracts the full Vibrant
swatch dict for each `workspace = N, <path>` mapping, and writes
~/.config/themes/workspace-accents.css with @define-color entries:

    @define-color ws1_vibrant        #...;
    @define-color ws1_light_vibrant  #...;
    @define-color ws1_dark_vibrant   #...;
    @define-color ws1_muted          #...;
    @define-color ws1_light_muted    #...;
    @define-color ws1_dark_muted     #...;
    @define-color ws1_on             #...;     /* black or white, contrast */
    /* …per workspace */

Missing swatches fall back: vibrant -> light_vibrant -> muted -> #888;
muted -> dark_muted -> light_muted -> #444. The CSS always has every
@define-color so consumers don't see gaps.

Sends a single SIGUSR2 to waybar at the end. Static file → consumer
waybar reads it once at startup; per-workspace switches don't re-read
or re-render anything CSS-related.

Wire via Hyprland exec.conf:
    exec-once = ~/.config/hyprmural/pill-accents.py
"""
from __future__ import annotations

import os
import pathlib
import re
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from vibrant import accent_for_bg, cached_swatches, resolve  # noqa: E402


CONFIG_PATH = pathlib.Path(
    os.environ.get("XDG_CONFIG_HOME", os.path.expanduser("~/.config"))
) / "hyprmural" / "hyprmural.conf"

OUTPUT_PATH = pathlib.Path(
    os.environ.get("XDG_CONFIG_HOME", os.path.expanduser("~/.config"))
) / "themes" / "workspace-accents.css"


def parse_workspaces(config_path: pathlib.Path) -> list[tuple[int, str]]:
    """Return [(workspace_int, image_abs_path), ...] for numeric workspaces."""
    out: list[tuple[int, str]] = []
    if not config_path.is_file():
        return out
    for raw in config_path.read_text().splitlines():
        # Strip comments
        line = raw.split("#", 1)[0].strip()
        if not line.startswith("workspace"):
            continue
        m = re.match(r"workspace\s*=\s*([^,]+),\s*(.+)$", line)
        if not m:
            continue
        ws, path = m.group(1).strip(), m.group(2).strip()
        if not ws.isdigit():
            continue
        path = os.path.expanduser(path)
        out.append((int(ws), path))
    return out


def write_css(workspaces: list[tuple[int, str]]) -> None:
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "/* workspace-accents.css — generated by hyprmural pill-accents.py.",
        " * Static colors per workspace, derived from each workspace's mapped",
        " * wallpaper via Vibrant-style extraction. Re-run pill-accents.py to",
        " * regenerate. */",
        "",
    ]
    for ws, path in sorted(workspaces):
        if not os.path.isfile(path):
            lines.append(f"/* ws{ws}: missing image '{path}' — using neutral fallback */")
            for slot in ("vibrant", "light_vibrant", "dark_vibrant"):
                lines.append(f"@define-color ws{ws}_{slot} #888888;")
            for slot in ("muted", "light_muted", "dark_muted"):
                lines.append(f"@define-color ws{ws}_{slot} #444444;")
            lines.append(f"@define-color ws{ws}_on #ffffff;")
            lines.append("")
            continue
        s = cached_swatches(path)
        # Fallback chains so every slot is always present
        v = resolve(s, "vibrant", "light_vibrant", "muted", default="888888")
        lv = resolve(s, "light_vibrant", "vibrant", "light_muted", default="bbbbbb")
        dv = resolve(s, "dark_vibrant", "vibrant", "dark_muted", default="555555")
        mu = resolve(s, "muted", "dark_muted", "light_muted", default="666666")
        lm = resolve(s, "light_muted", "muted", "light_vibrant", default="aaaaaa")
        dm = resolve(s, "dark_muted", "muted", "dark_vibrant", default="333333")
        bg = resolve(s, "bg", "dark_muted", "muted", default="333333")
        on = s.get("on", "ffffff")
        # Contrast-corrected accent: vibrant if it passes WCAG-AA against bg,
        # else the darker/lighter variant that does, else black/white fallback.
        fg = accent_for_bg(s, bg)

        lines.extend([
            f"/* ws{ws}: {os.path.basename(path)} */",
            f"@define-color ws{ws}_vibrant       #{v};",
            f"@define-color ws{ws}_light_vibrant #{lv};",
            f"@define-color ws{ws}_dark_vibrant  #{dv};",
            f"@define-color ws{ws}_muted         #{mu};",
            f"@define-color ws{ws}_light_muted   #{lm};",
            f"@define-color ws{ws}_dark_muted    #{dm};",
            f"@define-color ws{ws}_bg            #{bg};",
            f"@define-color ws{ws}_pill_fg       #{fg};",
            f"@define-color ws{ws}_on            #{on};",
            "",
        ])
    OUTPUT_PATH.write_text("\n".join(lines))


def reload_waybar() -> None:
    subprocess.run(["pkill", "-SIGUSR2", "waybar"], check=False, stdout=subprocess.DEVNULL,
                   stderr=subprocess.DEVNULL)


def main() -> int:
    workspaces = parse_workspaces(CONFIG_PATH)
    if not workspaces:
        sys.stderr.write(f"pill-accents: no numeric workspace mappings in {CONFIG_PATH}\n")
        return 1
    write_css(workspaces)
    reload_waybar()
    print(f"pill-accents: wrote {OUTPUT_PATH} ({len(workspaces)} workspace(s))")
    return 0


if __name__ == "__main__":
    sys.exit(main())
