#!/usr/bin/env python3
"""Generate per-workspace pill colors for waybar.

Reads hyprmural's per-workspace assignment file at
$XDG_RUNTIME_DIR/hyprmural/assignments.json — written by hyprmural at
startup (after pre-picking numeric workspaces 1..9 when randomize is on)
and refreshed on each new lazy pick. The CSS is then a pure function of
that map.

Two invocation modes:

  1. **Hook mode** — invoked from hyprmural's `hook =` chain on each
     per-output image change. Re-reads assignments.json (which hyprmural
     just refreshed), regenerates the CSS, and SIGUSR2s waybar only if
     the CSS content actually changed.

  2. **Seed mode** — invoked at session start (Hyprland exec-once) before
     the user has switched workspaces. Polls briefly for assignments.json
     to appear (hyprmural starts after Hyprland exec-once), then renders
     the full CSS and SIGUSR2s waybar.

The CSS always emits @define-color entries for ws1..ws9 (configurable via
PILL_ACCENTS_RANGE env, e.g. `1-12`). Workspaces missing from the
assignment map fall back to neutral grey so GTK doesn't choke on
undefined color references.

Wire via hyprmural.conf:
    hook = ~/.config/hyprmural/hook.sh

…and via Hyprland exec.conf:
    exec-once = ~/.config/hyprmural/pill-accents.py
"""
from __future__ import annotations

import json
import os
import pathlib
import subprocess
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from vibrant import accent_for_bg, cached_swatches, resolve  # noqa: E402


OUTPUT_PATH = pathlib.Path(
    os.environ.get("XDG_CONFIG_HOME", os.path.expanduser("~/.config"))
) / "themes" / "workspace-accents.css"

ASSIGNMENTS_PATH = pathlib.Path(
    os.environ.get("XDG_RUNTIME_DIR", "/tmp")
) / "hyprmural" / "assignments.json"


def parse_range(spec: str) -> list[int]:
    out: set[int] = set()
    for part in spec.split(","):
        part = part.strip()
        if not part:
            continue
        if "-" in part:
            lo, hi = part.split("-", 1)
            out.update(range(int(lo), int(hi) + 1))
        else:
            out.add(int(part))
    return sorted(out)


WORKSPACE_RANGE = parse_range(os.environ.get("PILL_ACCENTS_RANGE", "1-9"))


def load_assignments(timeout_s: float = 0.0) -> dict[int, str]:
    """Return {workspace_int: image_abs_path}. Polls up to timeout_s for
    the file to appear; returns {} if it never does."""
    deadline = time.monotonic() + max(timeout_s, 0.0)
    while True:
        if ASSIGNMENTS_PATH.is_file():
            try:
                raw = json.loads(ASSIGNMENTS_PATH.read_text())
            except (OSError, json.JSONDecodeError):
                return {}
            out: dict[int, str] = {}
            for k, v in raw.items():
                if isinstance(k, str) and k.isdigit() and isinstance(v, str) and v:
                    out[int(k)] = v
            return out
        if time.monotonic() >= deadline:
            return {}
        time.sleep(0.1)


def render_css(assignments: dict[int, str]) -> str:
    lines = [
        "/* workspace-accents.css — generated by hyprmural pill-accents.py.",
        " * Per-workspace colors derived from each workspace's current",
        " * wallpaper via Vibrant-style extraction. Source of truth is",
        " * $XDG_RUNTIME_DIR/hyprmural/assignments.json (written by",
        " * hyprmural). */",
        "",
    ]
    for ws in WORKSPACE_RANGE:
        path = assignments.get(ws)
        if not path or not os.path.isfile(path):
            lines.append(f"/* ws{ws}: no assignment — neutral fallback */")
            for slot in ("vibrant", "light_vibrant", "dark_vibrant"):
                lines.append(f"@define-color ws{ws}_{slot} #888888;")
            for slot in ("muted", "light_muted", "dark_muted"):
                lines.append(f"@define-color ws{ws}_{slot} #444444;")
            lines.append(f"@define-color ws{ws}_bg            #333333;")
            lines.append(f"@define-color ws{ws}_pill_fg       #ffffff;")
            lines.append(f"@define-color ws{ws}_on            #ffffff;")
            lines.append("")
            continue
        s = cached_swatches(path)
        v = resolve(s, "vibrant", "light_vibrant", "muted", default="888888")
        lv = resolve(s, "light_vibrant", "vibrant", "light_muted", default="bbbbbb")
        dv = resolve(s, "dark_vibrant", "vibrant", "dark_muted", default="555555")
        mu = resolve(s, "muted", "dark_muted", "light_muted", default="666666")
        lm = resolve(s, "light_muted", "muted", "light_vibrant", default="aaaaaa")
        dm = resolve(s, "dark_muted", "muted", "dark_vibrant", default="333333")
        bg = resolve(s, "bg", "dark_muted", "muted", default="333333")
        on = s.get("on", "ffffff")
        fg = accent_for_bg(s, bg)
        lines.extend([
            f"/* ws{ws}: {os.path.basename(path)} */",
            f"@define-color ws{ws}_vibrant       #{v};",
            f"@define-color ws{ws}_light_vibrant #{lv};",
            f"@define-color ws{ws}_dark_vibrant  #{dv};",
            f"@define-color ws{ws}_muted         #{mu};",
            f"@define-color ws{ws}_light_muted   #{lm};",
            f"@define-color ws{ws}_dark_muted    #{dm};",
            f"@define-color ws{ws}_bg            #{bg};",
            f"@define-color ws{ws}_pill_fg       #{fg};",
            f"@define-color ws{ws}_on            #{on};",
            "",
        ])
    return "\n".join(lines)


def reload_waybar() -> None:
    subprocess.run(
        ["pkill", "-SIGUSR2", "waybar"],
        check=False,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )


def write_if_changed(path: pathlib.Path, content: str) -> bool:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.is_file() and path.read_text() == content:
        return False
    path.write_text(content)
    return True


def main() -> int:
    # Hook mode passes env vars; seed mode (exec-once) doesn't. Hook mode
    # gets a fresh file (hyprmural just wrote it), seed mode may need to
    # wait briefly for hyprmural to come up after Hyprland exec-once.
    is_hook = bool(os.environ.get("HYPRMURAL_IMAGE"))
    timeout = 0.0 if is_hook else 30.0

    assignments = load_assignments(timeout)
    css = render_css(assignments)
    if write_if_changed(OUTPUT_PATH, css):
        reload_waybar()
        if not is_hook:
            print(f"pill-accents: wrote {OUTPUT_PATH} ({len(assignments)} workspace(s))")
    return 0


if __name__ == "__main__":
    sys.exit(main())
